title: Furong Wang 
logo: "/images/photo.png?raw=true" 
description: > 
  <br>
  Hi, Iâ€™m **Furong Wang**, a graduate student focused on data science, analytics, and machine learning. My work spans simulation modeling, marketing and web analytics, and real-world data applications.
  <br><br>
  Iâ€™m passionate about turning messy data into insights and sharing technical storytelling in clear, impactful ways.
  <br><br>
  ðŸŽ“ Currently at Boston University
  ðŸ“Š Favorite tools: R, Python, SQL
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
